title: jcvwaugh's blog
author: jcvwaugh
email: jcvwaugh@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is a blog and portfolio page, set up by jcvwaugh
  as part of the GitHub Pages with Jekyll lab.

# social links
twitter_username: zeroshark # DO NOT include the @ character, or else the build will fail!
github_username:  jcvwaugh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
